name: "Release"

on: [push]

jobs:
  build:
    if: ${{ github.repository_owner == 'LambdAurora' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3

        # Ensure that releases are not ran in parallel, this ensures that the latest commit is the latest release
        # See https://github.com/softprops/turnstyle
      - name: "Turnstyle"
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 3600
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Generate the build number based on tags to allow per branch build numbers, not something github provides by default.
      - name: "Generate build number"
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "build/${{ github.ref }}"

      - name: "Gradle Publish"
        run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          BRANCH_NAME: ${{ github.ref }}

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/